classdef graderutils
% graderutils.m
%
% Utilities that perform the actual grading. All one needs to do to
% implement a new grader is write a script that calls the
% generateTestCase() method > 1 times to generate a list of test cases and
% then pass them into runTestCases(), which does the actual grading.
%
% Brian Moore
% brimoor@umich.edu
%
% January 19, 2016
% September 15, 2016
% January 3, 2017
% April 11, 2017
%

    % Public constants
    % NOTE: Must match definitions in src/constants.py
    properties (GetAccess = public, Constant = true)
        % File postfixes
        GRADER_POSTFIX      = '_grader';
        SOLUTION_POSTFIX    = '_sol';

        % String denoting beginning of test results
        % This mutch match the TEST_RESULT_REGEX defined in ../src/main.py
        TEST_RESULT_REGEX   = '***** RESULTS *****';

        % Test status strings
        PASS                = 'pass';
        FAIL                = 'fail';
        ERROR               = 'error';
    end

    % Private constants
    properties (GetAccess = private, Constant = true)
        % Default test case arguments
        DEFAULT_TOL         = 0;
        DEFAULT_CHECKS      = [];
    end

    % Public static methods
    methods (Access = public, Static = true)
        %
        % Generate a test check
        %
        % Args:
        %   fcn: A function returning true/false
        %   arg: The output argument number to which to apply fcn()
        %   msg: The error message to display when fcn returns false
        %
        function check = generateCheck(fcn, arg, msg)
            check.fcn = fcn;
            check.arg = arg;
            check.msg = msg;
        end

        %
        % Generate a single test case
        %
        % Args:
        %   args: Function input. If > 1 inputs are required, pass them in
        %     as a cell
        %   tol: Optional numerical tolerance when checking output
        %     equality. The default value is 0
        %   checks: Optional array of test checks generated by
        %     generateCheck(). By default, empty
        %
        function testCase = generateTestCase(args, tol, checks)
            if ~exist('tol', 'var') || isempty(tol)
                tol = graderutils.DEFAULT_TOL;
            end
            if ~exist('checks', 'var') || isempty(checks)
                checks = graderutils.DEFAULT_CHECKS;
            end
            testCase.args = graderutils.wrapAsCell(args);
            testCase.tol = tol;
            testCase.checks = checks;
        end

        %
        % Run an array of test cases
        %
        % Args:
        %   testCases: A struct array of test cases generated by
        %     generateTestCase()
        %   graderName: The name of the _grader script that called this
        %     function
        %
        function runTestCases(testCases, graderName)
            try
                % Get functions
                baseName = graderutils.getBaseFilename(graderName);
                userFcn = str2func(baseName);
                solFcn = str2func(sprintf('%s%s', baseName, graderutils.SOLUTION_POSTFIX));

                % Run test cases
                for i = 1:numel(testCases)
                    testResults(i) = graderutils.runTestCase(testCases(i), userFcn, solFcn); %#ok
                end

                % Get test result
                success = [testResults.success];
                if all(success(:))
                    testStatus = graderutils.PASS;
                else
                    testStatus = graderutils.FAIL;
                end

                % Generate log file
                log = graderutils.generateLogFile(testResults);

                % Report test results
                graderutils.reportTestResults(testStatus, log);
            catch e
                % Handle error
                graderutils.reportTestResults(graderutils.ERROR);
                rethrow(e);
            end
        end

        %
        % Report test results
        %
        % Note: Only needs to be called if _grader script doesn't use the
        %       generateTestCase() and runTestCases() API, which would
        %       happen, e.g., if you're grading a script (not a function)
        %
        % Args:
        %   testStatus: PASS, FAIL, or ERROR
        %   log: A log string to append to results
        %
        function reportTestResults(testStatus, log)
            % Report results
            fprintf('%s\n', graderutils.TEST_RESULT_REGEX);
            fprintf('%s\n', testStatus);
            if exist('log', 'var') && ~isempty(log)
                fprintf('%s', log);
            end
        end
    end

    % Private static methods
    methods (Access = private, Static = true)
        % Run single test case
        function testResult = runTestCase(testCase, userFcn, solFcn)
            nout = nargout(solFcn);
            [userOut, userTime] = graderutils.callFcn(userFcn, testCase.args, nout);
            [solOut, solTime] = graderutils.callFcn(solFcn, testCase.args, nout);
            err = cellfun(@(user, sol) graderutils.computeError(user, sol), userOut, solOut);
            graderutils.applyTestChecks(userOut, testCase.checks);
            testResult = graderutils.generateTestResult(userTime, solTime, err, testCase.tol);
        end

        % Call function
        function [fcnOut, fcnTime] = callFcn(fcn, args, nout) %#ok
            % Call once to compile
            evalc('fcn(args{:})');

            % Now call for real
            tic();
            [~, fcnOut{1:nout}] = evalc('fcn(args{:})');
            fcnTime = toc();
        end

        % Apply test checks
        function applyTestChecks(out, checks)
            for i = 1:numel(checks)
                check = checks(i);
                if ~check.fcn(out{check.arg})
                    graderutils.raiseError(check.msg);
                end
            end
        end

        % Compute error
        function err = computeError(user, sol)
            graderutils.assertCompatibleTypes(user, sol); % Check types
            if ischar(sol)
                % String
                err = double(~strcmpi(user, sol));
            elseif graderutils.isNumericArray(sol)
                % Numeric array
                graderutils.assertCompatibleSizeArrays(user, sol); % Check sizes
                err = graderutils.maxAbsError(user, sol);
            else
                % Unsupported type
                msg = sprintf('Unsupported output type: %s', class(sol));
                graderutils.raiseError(msg);
            end
        end

        % Generate test result
        function testResult = generateTestResult(userTime, solTime, err, tol)
            testResult.userTime = userTime;
            testResult.solTime  = solTime;
            testResult.err = err;
            testResult.tol = tol;
            testResult.success = (max(err) <= tol);
        end

        % Get base filename for the input grader file
        function baseName = getBaseFilename(graderName)
            baseName = regexprep(graderName, [graderutils.GRADER_POSTFIX, '$'], '');
        end

        % Generate log file
        function log = generateLogFile(testResults)
            % Initialize message
            log = sprintf('%s\n', '----- Automated test log -----');

            % Append aggregate stats
            nPassed = sum([testResults.success]);
            log = sprintf('%s%d/%d tests passed\n', log, nPassed, numel(testResults));

            % Append test cases
            status = {graderutils.FAIL, graderutils.PASS};
            for i = 1:numel(testResults)
                testResult = testResults(i);
                errStr = sprintf('%.4g, ', testResult.err);
                log = [log, sprintf('\nTest case #%d:\n', i)]; %#ok
                log = [log, sprintf('user time = %.4gs\n', testResult.userTime)]; %#ok
                log = [log, sprintf('sol time  = %.4gs\n', testResult.solTime)]; %#ok
                log = [log, sprintf('error     = %s\n', errStr(1:(end - 2)))]; %#ok
                log = [log, sprintf('tolerance = %.4g\n', testResult.tol)]; %#ok
                log = [log, sprintf('status    = %s\n', status{1 + testResult.success})]; %#ok
            end
        end

        % Wrap input as cell, if necessary
        function args = wrapAsCell(args)
            if ~iscell(args)
                args = {args};
            end
        end

        % Determine if the input array is a vector
        function bool = isVector(X)
            bool = (ndims(X) - nnz(size(X) == 1)) == 1;
        end

        % Determine if the input is a numeric array
        function bool = isNumericArray(X)
            bool = isnumeric(X) || islogical(X);
        end

        % Standardize array
        function X = standardizeArray(X)
            if graderutils.isVector(X)
                X = X(:);
            end
        end

        % Compute max absolute error
        function err = maxAbsError(X, Y)
            err = full(max(abs(X(:) - Y(:))));
        end

        % Raise informative error if inputs aren't of compatible types
        function assertCompatibleTypes(user, sol)
            % Convenience function for throwing the error
            function throwWrongDataTypeError()
                graderutils.raiseError(sprintf('Received output of class "%s" but expected output of class "%s"', class(user), class(sol)));
            end

            % Check data types
            if ischar(sol)
                % String
                if ~ischar(user)
                    throwWrongDataTypeError();
                end
            elseif graderutils.isNumericArray(sol)
                % Numeric array
                if ~graderutils.isNumericArray(user)
                    throwWrongDataTypeError();
                end
            else
                % Unsupported type
                graderutils.raiseError(sprintf('Unsupported output type: %s', class(sol)));
            end
        end

        % Raise informative exception if inputs aren't of compatible sizes
        function assertCompatibleSizeArrays(user, sol)
            % Check compatibility
            if ~isequal(size(graderutils.standardizeArray(user)), size(graderutils.standardizeArray(sol)))
                graderutils.raiseError(sprintf('Received array of size %s but expected array of size %s', mat2str(size(user)), mat2str(size(sol))));
            end
        end

        % Raise error
        function raiseError(msg)
            pad = repmat('*', 1, 3);
            bar = repmat('*', 1, numel(msg) + 2);
            error(sprintf('\n%s%s%s\n%s %s %s\n%s%s%s', ...
                pad, bar, pad, ...
                pad, msg, pad, ...
                pad, bar, pad)); %#ok
        end
    end

    % Private methods
    methods (Access = private)
        % Private constructor
        function this = graderutils(varargin)
            % Empty
        end
    end
end
