#!/usr/bin/env python
# graderutils.py
#
# Utilities that perform the actual grading. All one needs to do to implement
# a new grader is write a script that calls the generateTestCase() method > 1
# times to generate a list of test cases and then pass them into runTestCases(),
# which does the actual grading.
#
import contextlib
import importlib
import os
import re
import time

import numpy as np

GRADER_POSTFIX = "_grader"
SOLUTION_POSTFIX = "_sol"

# This must match the TEST_RESULT_REGEX defined in ../src/main.py
# We could import it, but because other graderutils are in other languages
# we define it again here to be consistent
TEST_RESULT_REGEX = "***** RESULTS *****"

PASS = "pass"
FAIL = "fail"
ERROR = "error"

_DEFAULT_TOL = 0


#
# Generate a test check
#
# Args:
#   fcn: A function returning true/false
#   arg: The output argument number (1-BASED) to which to apply fcn()
#   msg: The error message to display when fcn returns false
#
def generateCheck(fcn, arg, msg):
    return {
        "fcn": fcn,
        "arg": arg,
        "msg": msg,
    }


#
# Generate a single test case
#
# Args:
#   args: Function input. If > 1 inputs are required, pass them in as a tuple
#   kwargs: Optional dictionary of keyword arguments, By default, {}
#   tol: Optional numerical tolerance when checking output equality. The default
#     value is 0
#   checks: Optional array of test checks generated by generateCheck(). By
#     default, empty
#
def generateTestCase(args, kwargs=None, tol=_DEFAULT_TOL, checks=None):
    return {
        "args": _wrapAsTuple(args),
        "kwargs": kwargs if kwargs else {},
        "tol": tol,
        "checks": checks if checks is not None else [],
    }


#
# Run an array of test cases
#
# Args:
#   testCases: An array of test cases generated by generateTestCase()
#   graderName: The name of the _grader script that called this function
#
def runTestCases(testCases, graderName):
    try:
        baseName = _getBaseFilename(graderName)
        userFcn = _getEmbeddedFunction(baseName)
        solFcn = _getEmbeddedFunction(baseName + SOLUTION_POSTFIX)
        testResults = [_runTestCase(testCase, userFcn, solFcn) for testCase in testCases]
        success = [testResult["success"] for testResult in testResults]
        testStatus = PASS if all(success) else FAIL
        log = _generateLogFile(testResults)
        reportTestResults(testStatus, log)
    except Exception:
        reportTestResults(ERROR)
        raise


#
# Report test results
#
# Note: Only needs to be called if _grader script doesn't use the
#       generateTestCase() and runTestCases() API, which would happen, e.g.,
#       if you're grading a script (not a function)
#
# Args:
#   testStatus: PASS, FAIL, or ERROR
#   log: A log string to append to results
#
def reportTestResults(testStatus, log=None):
    print(TEST_RESULT_REGEX)
    print(testStatus)
    if log:
        print(log)


class NoStdout(contextlib.AbstractContextManager):
    def __enter__(self):
        self._devnull = open(os.devnull, "w")
        self._redirect = contextlib.redirect_stdout(self._devnull)
        self._redirect.__enter__()
        return self

    def __exit__(self, *args):
        result = self._redirect.__exit__(*args)
        self._devnull.close()
        return result


def _runTestCase(testCase, userFcn, solFcn):
    userOut, userTime = _callFcn(userFcn, testCase["args"], testCase["kwargs"])
    solOut, solTime = _callFcn(solFcn, testCase["args"], testCase["kwargs"])
    err = [_computeError(user, sol) for (user, sol) in zip(userOut, solOut)]
    _applyTestChecks(userOut, testCase["checks"])
    return _generateTestResult(userTime, solTime, err, testCase["tol"])


def _callFcn(fcn, args, kwargs):
    with NoStdout():
        # Call once to compile
        fcn(*args, **kwargs)

        start = time.time()
        fcnOut = _wrapAsTuple(fcn(*args, **kwargs))
        fcnTime = time.time() - start
        return (fcnOut, fcnTime)


def _applyTestChecks(out, checks):
    for check in checks:
        if not check["fcn"](out[check["arg"] - 1]):
            _raiseError(check["msg"], exception=AssertionError)


def _computeError(user, sol):
    _assertCompatibleTypes(user, sol)
    if isinstance(sol, str):
        return float(not (user == sol))
    elif _isNumericArray(sol):
        _assertCompatibleSizeArrays(user, sol)
        return _maxAbsError(user, sol)
    else:
        _raiseError("Unsupported output type: %s" % type(sol), exception=ValueError)


def _generateTestResult(userTime, solTime, err, tol):
    return {
        "userTime": userTime,
        "solTime": solTime,
        "err": err,
        "tol": tol,
        "success": (max(err) <= tol),
    }


def _getBaseFilename(graderName):
    filename = os.path.splitext(os.path.basename(graderName))[0]
    return re.sub(GRADER_POSTFIX + "$", "", filename)


# Get function with name fcnStr embedded in fcnStr.py module
def _getEmbeddedFunction(fcnStr):
    module = importlib.import_module(fcnStr)
    return getattr(module, fcnStr)


def _generateLogFile(testResults):
    log = "----- Automated test log -----\n"
    nPassed = sum([testResult["success"] for testResult in testResults])
    log += "%d/%d tests passed\n" % (nPassed, len(testResults))
    for idx, testResult in enumerate(testResults):
        errStr = ", ".join([("%.4g" % e) for e in testResult["err"]])
        log += "\nTest case #%d:\n" % (idx + 1)
        log += "user time = %.4gs\n" % testResult["userTime"]
        log += "sol time  = %.4gs\n" % testResult["solTime"]
        log += "error     = %s\n" % errStr
        log += "tolerance = %.4g\n" % testResult["tol"]
        log += "status    = %s\n" % (PASS if testResult["success"] else FAIL)
    return log


# If the input is not a tuple, wrap it as a one-element tuple
def _wrapAsTuple(obj):
    if obj is not None and not isinstance(obj, tuple):
        obj = (obj,)
    return obj


# Convert to array, if necessary. Doesn't copy array, if possible
def _toArray(array_like):
    if np.isscalar(array_like):
        return np.asarray([array_like])
    elif isinstance(array_like, (list, tuple)):
        return np.asarray(array_like)
    else:
        return array_like


def _isVector(array_like):
    a = _toArray(array_like)
    return (a.ndim == 1) or (a.ndim - a.shape.count(1) <= 1)


def _isNumericArray(array_like):
    try:
        a = _toArray(array_like)
        if not np.iscomplexobj(a):
            _ = a.astype(float)
        return True
    except (TypeError, ValueError):
        return False


def _numel(array_like):
    return np.prod(_toArray(array_like).shape)


def _standardizeArray(array_like):
    a = _toArray(array_like).copy()
    if _isVector(a):
        # Convert to 2D column vector
        if a.ndim != 2:
            # Must be an array, so we can set shape directly
            a.shape = (_numel(a), 1)
        elif a.shape[1] > a.shape[0]:
            # Might be a sparse matrix, so use transpose
            a = a.T
    return a


def _maxAbsError(user, sol):
    return abs(_standardizeArray(user) - _standardizeArray(sol)).max()


def _assertCompatibleTypes(user, sol):
    def _raiseWrongTypeException():
        _raiseError(
            "Received output of %s but expected output of %s" % (type(user), type(sol)),
            exception=TypeError,
        )

    if isinstance(sol, str):
        if not isinstance(user, str):
            _raiseWrongTypeException()
    elif _isNumericArray(sol):
        if not _isNumericArray(user):
            _raiseWrongTypeException()
    else:
        _raiseError("Unsupported output type: %s" % type(sol), exception=ValueError)


def _assertCompatibleSizeArrays(user, sol):
    user = _toArray(user)
    sol = _toArray(sol)
    if _standardizeArray(user).shape != _standardizeArray(sol).shape:
        _raiseError(
            "Received array of size %s but expected array of size %s"
            % (str(user.shape), str(sol.shape)),
            exception=ValueError,
        )


def _raiseError(msg, exception=Exception):
    pad = "*" * 3
    bar = "*" * (len(msg) + 2)
    raise exception(
        "\n\n%s%s%s\n%s %s %s\n%s%s%s\n" % (pad, bar, pad, pad, msg, pad, pad, bar, pad)
    )
