#!/usr/bin/env julia
# graderutils.jl
#
# Utilities that perform the actual grading. All one needs to do to implement
# a new grader is write a script that calls the generateTestCase() method > 1
# times to generate a list of test cases and then pass them into runTestCases(),
# which does the actual grading.
#
# Brian Moore
# brimoor@umich.edu
#
# January 3, 2017
# April 11, 2017
# July 28, 2017
# November 10, 2017
#
#
# Steven Whitaker
# stwhit@umich.edu
#
# August 27, 2018
# - Changes to avoid deprecation warnings in Julia 0.7
# - Avoid precompilation to allow other users to use this module
# - Add path to stdlib to LOAD_PATH
# - Modify _getEmbeddedFunction to make it so the included file
#   is included in the temp module
#
__precompile__(false)
module graderutils

push!(LOAD_PATH, "/home/eecs551/julia-0.7.0/share/julia/stdlib/v0.7")
using Printf

#-------------------------------------------------------------------------------
# Public constants
# NOTE: Must match definitions in src/constants.py
#-------------------------------------------------------------------------------
# File postfixes
GRADER_POSTFIX    = "_grader"
SOLUTION_POSTFIX  = "_sol"

# String denoting beginning of test results
# This mutch match the TEST_RESULT_REGEX defined in ../src/main.py
TEST_RESULT_REGEX = "***** RESULTS *****"

# Test status strings
PASS              = "pass"
FAIL              = "fail"
ERROR             = "error"

#-------------------------------------------------------------------------------
# Private constants
#-------------------------------------------------------------------------------
# Default test case arguments
_DEFAULT_TOL      = 0
_DEFAULT_CHECKS   = []

#-------------------------------------------------------------------------------
# Public methods
#-------------------------------------------------------------------------------
#
# Generate a test check
#
# Args:
#   fcn: A function returning true/false
#   arg: The output argument number to which to apply fcn()
#   msg: The error message to display when fcn returns false
#
function generateCheck(fcn, arg, msg)
    return Dict(
        "fcn" => fcn,
        "arg" => arg,
        "msg" => msg,
    )
end

#
# Generate a single test case
#
# Args:
#   args: Function input. If > 1 inputs are required, pass them in as a tuple
#   kwargs: Optional tuple of keyword arguments, where each keyword argument is
#     itself specified as a tuple of the form (Symbol, val). For example, to
#     set a keyword argument "x=5", pass kwargs=((:x, 5),). By default, ()
#   tol: Optional numerical tolerance when checking output equality. The default
#     value is 0
#   checks: Optional array of test checks generated by generateCheck(). By
#     default, empty
#
function generateTestCase(args; kwargs=(), tol=_DEFAULT_TOL, checks=_DEFAULT_CHECKS)
    return Dict(
        "args" => _wrapAsTuple(args),
        "kwargs" => kwargs,
        "tol" => tol,
        "checks" => checks,
    )
end

#
# Run an array of test cases
#
# Args:
#   testCases: An array of test cases generated by generateTestCase()
#   graderName: The name of the _grader script that called this function
#
function runTestCases(testCases, graderName)
    try
        # Get functions
        baseName = _getBaseFilename(graderName)
        userFcn = _getEmbeddedFunction(baseName; moduleName="user")
        solFcn = _getEmbeddedFunction(baseName * SOLUTION_POSTFIX; moduleName="sol")

        # Run test cases
        testResults = [_runTestCase(testCase, userFcn, solFcn) for testCase in testCases]

        # Handle results
        success = [testResult["success"] for testResult in testResults]
        testStatus = all(success) ? PASS : FAIL

        # Generate log file
        log = _generateLogFile(testResults)

        # Report test results
        reportTestResults(testStatus; log=log)
    catch
        # Handle error
        reportTestResults(ERROR)
        rethrow()
    end
end

#
# Report test results
#
# Note: Only needs to be called if _grader script doesn't use the
#       generateTestCase() and runTestCases() API, which would  happen, e.g.,
#       if you're grading a script (not a function)
#
# Args:
#   testStatus: PASS, FAIL, or ERROR
#   log: A log string to append to results
#
function reportTestResults(testStatus; log=nothing)
    println(TEST_RESULT_REGEX)
    println(testStatus)
    if !isa(log, Nothing)
        println(log)
    end
end

# Context manager that suppresses STDOUT
#
# Syntax:
#
#   with_NoStdout() do
#       # Commands here
#   end
#
function with_NoStdout(executeBody::Function)
    # Suppress STDOUT
    orig_stdout = stdout
    redirect_stdout()
    try
        # Execute body
        executeBody()
    finally
        # Reconnect STDOUT
        redirect_stdout(orig_stdout)
    end
end

# Implementation of include() that searches on LOAD_PATH for the file
#
# NOTE: file should be a file name (with extension) only, NOT an absolute or
#       relative path
#
function include_from_LOAD_PATH(file)
    Base.include(Main, _getAbsPath(file))
end

#-------------------------------------------------------------------------------
# Private methods
#-------------------------------------------------------------------------------
# Run single test case
function _runTestCase(testCase, userFcn, solFcn)
    userOut, userTime = _callFcn(userFcn, testCase["args"], testCase["kwargs"])
    solOut, solTime = _callFcn(solFcn, testCase["args"], testCase["kwargs"])
    err = [_computeError(user, sol) for (user, sol) in zip(userOut, solOut)]
    _applyTestChecks(userOut, testCase["checks"])
    return _generateTestResult(userTime, solTime, err, testCase["tol"])
end

# Call function
function _callFcn(fcn, args, kwargs)
    with_NoStdout() do
        if VERSION >= v"0.6"
            inner() = fcn(args...; kwargs...)

            # Call once to compile
            Base.invokelatest(inner)

            # Now call for real
            fcnTime = @elapsed fcnOut = _wrapAsTuple(Base.invokelatest(inner))
            return fcnOut, fcnTime
        else
            # Call once to compile
            fcn(args...; kwargs...)

            # Now call for real
            tic()
            fcnOut = _wrapAsTuple(fcn(args...; kwargs...))
            fcnTime = toq()
            return fcnOut, fcnTime
        end
    end
end

# Apply test checks
function _applyTestChecks(out, checks)
    for check in checks
        if !check["fcn"](out[check["arg"]])
            _raiseError(check["msg"]; exception=AssertionError)
        end
    end
end

# Compute error
function _computeError(user, sol)
    _assertCompatibleTypes(user, sol) # Check types
    if isa(sol, String)
        # String
        return float(!(user == sol))
    elseif _isNumericArray(sol)
        # Numeric array
        _assertCompatibleSizeArrays(user, sol) # Check sizes
        return _maxAbsError(user, sol)
    else
        # Unsupported type
        _raiseError(@sprintf("Unsupported output type: %s", typeof(sol)))
    end
end

# Generate test result
function _generateTestResult(userTime, solTime, err, tol)
    return Dict(
        "userTime" => userTime,
        "solTime" => solTime,
        "err" => err,
        "tol" => tol,
        "success" => (maximum(err) <= tol),
    )
end

# Get absolute path to given file
function _getAbsPath(file)
    # Search for file on LOAD_PATH
    for path in LOAD_PATH
        abs_path = joinpath(path, file)
        if isfile(abs_path)
            return abs_path
        end
    end

    # Couldn't find file
    _raiseError(@sprintf("Couldn't find file %s on LOAD_PATH", file); exception=ErrorException)
end

# Get base filename for the input grader file
function _getBaseFilename(graderName)
    filename = splitext(basename(graderName))[1]
    return replace(filename, Regex("$GRADER_POSTFIX\$") => "")
end

# Get function with name fcnStr embedded in fcnStr.jl file
#
# Implementation details
#   Dynamically creates a "moduleName" module
#   Includes fcnStr.jl in the module
#   Returns the fcnStr method from the module
#
## Old version that didn't require students to name their function correctly
#function _getEmbeddedFunction(fcnStr; moduleName="tmp")
#    cmds = "module $moduleName; " *
#           "using graderutils: include_from_LOAD_PATH; " *
#           "fcn = include_from_LOAD_PATH(\"$fcnStr.jl\"); " *
#           "end; " *
#           "$moduleName.fcn"
#    return eval(Meta.parse(cmds))
#end
# Work-around to make sure students correctly name their function. Essentially,
# I just copied the contents of include_from_LOAD_PATH into the new temp module
# because using include_from_LOAD_PATH would load the function into a scope that
# was not accessible after the end of the module.
function _getEmbeddedFunction(fcnStr; moduleName="tmp")
    cmds = "module $moduleName; " *
           "found = false; abs_path = \"\"; " *
           "for path in LOAD_PATH; global abs_path = joinpath(path, \"$fcnStr.jl\"); " *
           "if isfile(abs_path); global found = true; break; end; end; " *
           "if !found; msg = \"Couldn't find file $fcnStr.jl on LOAD_PATH\"; " *
           "pad = \"*\" ^ 3; bar = \"*\" ^ (length(msg) + 2); " *
           "throw(ErrorException(\"\\n\\n\$pad\$bar\$pad\\n\$pad \$msg \$pad\\n\$pad\$bar\$pad\\n\")); " *
           "end; " *
           "include(abs_path); " *
           "end; " *
           "$moduleName.$fcnStr"
    return eval(Meta.parse(cmds))
end

#=
# Get function with name fcnStr embedded in fcnStr.jl file
#
# NOTE
#  Method-override WARNINGs will occur if the solution file defines functions
#  of the same name as functions from the user's submission. This could even
#  lead to erroneous behavior (cf. github.com/JuliaLang/julia/issues/265)
#
function _getEmbeddedFunction(fcnStr)
    include_from_LOAD_PATH("$fcnStr.jl")
    return getfield(current_module(), Symbol(fcnStr))
end
=#

# Generate log file
function _generateLogFile(testResults)
    # Initialize mesasge
    log = "----- Automated test log -----\n"

    # Append aggregate stats
    nPassed = sum([testResult["success"] for testResult in testResults])
    log *= @sprintf("%d/%d tests passed\n", nPassed, length(testResults))

    # Append test case stats
    for (idx, testResult) in enumerate(testResults)
        errStr = join([@sprintf("%.4g", err) for err in testResult["err"]], ", ")
        log *= @sprintf("\nTest case #%d:\n", idx)
        log *= @sprintf("user time = %.4gs\n", testResult["userTime"])
        log *= @sprintf("sol time  = %.4gs\n", testResult["solTime"])
        log *= @sprintf("error     = %s\n", errStr)
        log *= @sprintf("tolerance = %.4g\n", testResult["tol"])
        log *= @sprintf("status    = %s\n", testResult["success"] ? PASS : FAIL)
    end

    # Return log
    return log
end

# If the input is not a tuple, wrap it as a one-element tuple
function _wrapAsTuple(obj)
    return isa(obj, Nothing) || isa(obj, Tuple) ? obj : (obj,)
end

# Convert to array, if necessary. Doesn't copy array, if possible
function _toArray(array_like)
    return isa(array_like, AbstractArray) ? array_like : collect(array_like)
end

# Determine if the input array_like object is a vector
function _isVector(array_like)
    a = _toArray(array_like)
    return (ndims(a) <= 2) && (count(d -> (d != 1), size(a)) <= 1)
end

# Determine if the input is a numeric array_like object
function _isNumericArray(array_like)
    return eltype(array_like) <: Number
end

# Get number of elements in array_like
function _numel(array_like)
    return length(_toArray(array_like))
end

# Standardize array
function _standardizeArray(array_like)
    a = _toArray(array_like)
    return _isVector(a) ? vec(a) : a
end

# Compute max absolute error
function _maxAbsError(user, sol)
    return maximum(abs, _standardizeArray(user) - _standardizeArray(sol))
end

# Raise informative error if inputs aren't of compatible types
function _assertCompatibleTypes(user, sol)
    # Convenience function for raising the exception
    function _raiseWrongTypeException()
        _raiseError(@sprintf("Received output of %s but expected output of %s", typeof(user), typeof(sol)))
    end

    # Check data types
    if isa(sol, String)
        # String
        if !isa(user, String)
            _raiseWrongTypeException()
        end
    elseif _isNumericArray(sol)
        # Numeric array
        if !_isNumericArray(user)
            _raiseWrongTypeException()
        end
    else
        # Unsupported type
        _raiseError(@sprintf("Unsupported output type: %s", typeof(sol)))
    end
end

# Raise informative error if input array_like objects aren't of compatible sizes
function _assertCompatibleSizeArrays(user, sol)
    # Parse inputs
    user = _toArray(user)
    sol = _toArray(sol)

    # Check compatibility
    if size(_standardizeArray(user)) != size(_standardizeArray(sol))
        _raiseError(@sprintf("Received array of size %s but expected array of size %s", size(user), size(sol)))
    end
end

# Raise error
function _raiseError(msg; exception=ArgumentError)
    pad = "*" ^ 3
    bar = "*" ^ (length(msg) + 2)
    throw(exception("\n\n$pad$bar$pad\n$pad $msg $pad\n$pad$bar$pad\n"))
end

end
